#devModes:
#  oidcSmartIntrospect:
#    enabled: true
#    fakeUid:
#      subject: subject
#      issuer: issuer
#      email: a@mail.it
#      emailVerified: true
#      token: header.body.signature
#      roles:
#        - admin
#      allRoles:
#        - ids:admin
#      audience: ids
#      expires: 3600
#      issuedAt: -1
#      active: true
mode: access-proxy

oidc:
  issuers:
  - issuer: https://issuer.castle_black.com
    introspection_endpoint: https://issuer.castle_black.com/introspect
    client:
      client_id: the_wall
      client_secret: the_key_of_the_wall

admissionControl:
  url: http://opa:8181/v1/data
  dryRun:
    enabled: false
    header: 'x-authorizer'

targets:
  path: /**
  upstream: http://httpbin.org
  routes: []
  #  - path: /_dev
  #    upstream: http://httpbin.org
  rewrite: []
  #  - match: ^/_dev
  #    rewrite: '/headers'

storage:
  kind: InMemory
  specs:
    stdTTL: 86400 #24h

server:
  # max_body_limit: 100k
  http:
    enable: true
    port: 3000
  # to be implemented
  https:
    enable: false
    port: 3001
  max_header_size: 8192 #????? ndo' stata????
  proxy:
    # http://expressjs.com/en/guide/behind-proxies.html
    # loopback - 127.0.0.1/8, ::1/128
    # linklocal - 169.254.0.0/16, fe80::/10
    # uniquelocal - 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7
    - loopback
    - linklocal
    - uniquelocal
  healthchecks:
    readiness: /healthcheck/ready
    liveness: /healthcheck
    timeout: 2000 #2sec

logLevel: error
headers:
  proxy:
    token: token
    expiresin: expiresIn
    subject: subject
    email: email
    family-name: familyName
    given-name: givenName
    roles: roles
    username: name
    userid: username
    all-roles: allRoles
    issuer: issuer
    audience: audience
  noProxy:
    - authorization

# RP MODE
#relying_party:
#  on_success_redirect: /
#  on_fail_redirect: /
#  oidc_base_path: /oidc
#  oidc_paths:
#    login: /login
#    callback: /callback
#  rules:
#    - route: /**
#      methods:
#        - all


devModes:
  oidcSmartIntrospect:
    enabled: false
    fakeUid:
      subject: subject
      issuer: issuer
      email: a@mail.it
      emailVerified: true
      token: header.body.signature
      roles:
        - pippo
      allRoles:
        - fff:admin
      audience: fff
      expires: 3600
      issuedAt: -1
      active: true

